name = "glassfroguk"
compatibility_date = "2024-02-04"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".vercel/output/static"

[build.upload]
format = "service-worker"

[build.environment]
NODE_VERSION = "20.0.0"

[build_output_directory]
value = ".vercel/output/static"