name = "glassfroguk"
compatibility_date = "2024-02-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages@1"

[build.environment]
NODE_VERSION = "20.0.0"

[[build.upload]]
format = "service-worker"
dir = ".vercel/output/static"
main = ".vercel/output/static/_worker.js"

[env.production]
name = "glassfroguk-production"

[env.preview]
name = "glassfroguk-preview"